### PR TITLE
Updated the logo of USF and deleted old logo files.

### PR DESCRIPTION
**Pull request by jailby**
Also set at false the attribute to display the title. 'Mobullity' will not appear anymore

### CODE REVIEW

**Comment by barbeau** [comment]
@jailby Thanks!  Could you please include a screenshot of the new look also in a comment here?

**Comment by jailby** [comment]
The following screenshot is how the website will look with this changes:
image

**Comment by barbeau** [comment]
Great!  How about mobile?

**Comment by jailby** [comment]
Good catch!
The logo does not appear on mobile.

I check http://mobullity.forest.usf.edu/ and the previous logo is not showing up either.

@jmfield2 did you ever notice this problem before?

The problem come from the screen of the Mobile being too small. If you try, on the production, on desktop, to re-size the window the images, such as the logo and the "sharing" images, will disappear.

We would need to look into how the function to fit things into the screen work.

The buttons "trip planner" and "layers" will be removed at some point but even after their removal it was not enough to make the logo fit into a mobile screen (I tested it).

**Comment by jmfield2** [comment]
BTW The screenshot looks really nice. :+1:  
I think I have seen the logo disappear on smaller screens before, but haven't really looked much into it until now.

Looks like it is hidden by default and is only shown on sizes larger than 768px via @media rules in style.css @ 
https://github.com/CUTR-at-USF/usf-mobullity/blob/b6e34e96d643f44ff8626cc7af1a9a55df4f9b07/src/client/style.css#L269
and
https://github.com/CUTR-at-USF/usf-mobullity/blob/b6e34e96d643f44ff8626cc7af1a9a55df4f9b07/src/client/style.css#L1117

If you remove the 'display:none' from the first, it should fix it.

**Comment by jailby** [comment]
Thanks @jmfield2 it is working now.

The following is a screenshot, on mobile, of what the website looks like now.

Also keep in mind that the button "trip planner" and "layer" will be replace by the single button menu and it will look a lot better.

image

**Comment by barbeau** [comment]
Nice!!  Looks really good!  Great job JB!

**Comment by jailby** [comment]
@barbeau can I merge it?

**Comment by barbeau** [comment]
Done!  Thanks again!

**Comment by jailby** [comment]
I'm not totally sure but I think that the code [here](https://github.com/CUTR-at-USF/usf-mobullity/blob/b6e34e96d643f44ff8626cc7af1a9a55df4f9b07/src/client/style.css#L277) until [here](https://github.com/CUTR-at-USF/usf-mobullity/blob/b6e34e96d643f44ff8626cc7af1a9a55df4f9b07/src/client/style.css#L363), was there for the previous logo.

@jmfield2 can you confirm or deny? I think from my understanding of the code that this is setting up the background for the logo but it will be "overwrite" by the "banner's" css.

If it is the case we could clean up this code for the seek of clarity.

**Comment by jailby** [comment]
@jmfield2 I believe that the css defined in the section mentioned in the above comment is specific to the official OTP. The color are multiple taint of blue. (it is still present in the official upstream repository)

Removing this section seem to not affect the website.

**Pull request merged**
