### PR TITLE
Changed the color of the line in the inner part of the layer widget t…

### PR DESCRIPTION
**Pull request by jailby**
**Don't merge**

This PR has been done through WebStorm from intelliJ.

@barbeau as you can see the problem is still there.

I'm going to look into it more and try to find the problem. I just create this PR to give you a visual of what's going on.

### CODE REVIEW

**Comment by barbeau** [comment]
Yeah, interesting.  It's definitely whitespace, because if you look at this URL (which shows only non-whitespace changes) the other change disappears:
https://github.com/CUTR-at-USF/usf-mobullity/pull/189/files?w=1

Seems to me like `git config --global core.autocrlf input` should fix this, but obviously it's not.

Is it possible that you have core.autocrlf set for the local project to something other than "input"?  In other words, local project level Git settings may be overriding global Git settings on your machine?

@jmfield2 It looks like JB's editor is replacing the newlines from the lines from your commit on the bluelights (see the diff in this PR).  What is your local `core.autocrlf` setting?  Any idea why your newlines might be different?  I think you're working on Linux too, right?

**Comment by jmfield2** [comment]
My core.autocrlf was not set so perhaps that is where it came from - I'll
set it to input and check things on my side

**Comment by barbeau** [comment]
I'd probably go ahead and merge this even with the whitespace issue.  Hopefully with @jmfield2 changing settings on his end it won't happen again in the future.

**Comment by jailby** [comment]
So if try to merge it tells me that the hole file "
style.css" has been changed.

mobulity is ahead of this branch. Now I got them together but if I look what happen with `git diff` I have the following:

```
diff --cc src/client/style.css
index 496880c,a16a3dc..0000000
--- a/src/client/style.css
+++ b/src/client/style.css
@@@ -977,12 -977,16 +977,25 @@@ p#splash-text span 
```

I'm still looking into this. Ijust wanted to update you in case you wondering why it is still not merged.

**Comment by barbeau** [comment]
@jailby Thanks for the update.  Did you change core.autocrlf back to input?

If your on the branch that contains the commit, you can "undo" the commit and re-stage the contents with `git reset HEAD^`.  Then you'd need to make sure everything looks good, commit again, and force push to this same remote branch.

**Comment by jailby** [comment]
Yes its what I'm doing.

I create a new branch and went to the head of upstream mobulityrebase. I typed `git config --global core.autocrlf input`  once again to make sure but if I open "style.css" and save it (without modifying anything) then `git diff` tells me I changed the whole file.

I also just checked my `~/.gitconfig` and `autocrlf` is set to `input`

**Comment by jailby** [comment]
Changed done through PR #190

**Pull request closed without merging**
