### PR TITLE
Added the favicon to mobullity. The favicon has been fetch from usf.edu.

### PR DESCRIPTION
**Pull request by jailby**
This one should only have one commit which the addition of the image and the link in index.html

### CODE REVIEW

**Comment by jailby** [comment]
fixes #133

**Comment by jailby** [comment]
fixes #130

**Comment by jailby** [comment]
@barbeau is this ok to merge?

I remember we discuss the size of the image and since usf.edu does not have a different size we conclude that we won't add a different size. Am I right?

**Comment by barbeau** [comment]
Yes, OK to merge.

**Pull request merged**
