### PR TITLE
WIP. Added the menu button. Partially populate the menu. 

### PR DESCRIPTION
**Pull request by jailby**
The trip planner and layers widget are linked to their respective button in the menu (the older button have been removed).

@jmfield2 Can you take a look at this and see why the "z-index" tag is not sufficient to make the menu appear on top.

Also, for the submenu I found some material on the wiki of the github of MDL. They provide for example [this website](http://www.richmediagallery.com/#) that does what I want.

**Please, do not merge. More commit are necessary**

### CODE REVIEW

**Comment by jailby** [comment]
Also, here is two screenshot of how it looks with these changes on my local:
image

image

**Comment by jmfield2** [comment]
I think I was able to fix the z-index issues causing this issue (patch attached) - basically, the largest z-index appears on top of lower z-index values and the menu had -1 (apparently by default via the css?) 

I override that first, and then lower the #map and #otp-widget class z-index to be lower so that the menu can stay on top.

[0001-Fix-z-indexes-for-new-menu-and-widgets-map.txt](https://github.com/CUTR-at-USF/usf-mobullity/files/24161/0001-Fix-z-indexes-for-new-menu-and-widgets-map.txt)

**Comment by jailby** [comment]
If you do a PR on this branch of my repository will it appear in this PR once I merge the change on my repository?

**Comment by jmfield2** [comment]
Hmm its easiest just to apply the changes in my patch in your local branch and push it to your origin
If it's the same branch, this PR will show the new commits

**Comment by jailby** [comment]
Can you send me your style.css file?

Does it work on your local?

I tried to manually change every "z-index" tag that you changed but it does not work. A diff file is not easy to read and I probably made a mistake somewhere. I would be easier if I just overwrite my style.css by yours.

**Comment by jailby** [comment]
@jmfield2 Hey I need some help with javascript.

I want to link the "Help" button to the icon legend.

So I localize in [config.js that the icon legend widget was declared.](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/config.js#L174)

And [here](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/core/WidgetManagerMenu.js#L56) I believe is when this widget is used and more specifically actually opened [here](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/core/WidgetManagerMenu.js#L68).

From [this line](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/core/WidgetManagerMenu.js#L64) I assumed that I should do the following:

```
<li class="mdl-menu__item" onClick="javascript:otp.config.infoWidgets[0].show();" >Help</li> 
```

But this is not working. I figured that you might have an idea of how to properly do it. I'm still looking into it but if you see that and can help me out I would appreciate.

**Comment by jmfield2** [comment]
Try webapp.infoWidgets. instead of otp.config because the otp.config is
just a dictionary holding the settings for the widget and not the
instantiated widget object but it looks like (from the line above) that the
actual instantiated object should be at webapp.infoWidgets[0]

**Comment by jailby** [comment]
I think you are right about the "webapp" part but it is still not working.

I think I might know why. If you look at [this line](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/core/WidgetManagerMenu.js#L67)
`this.id` is given instead of `0`.

Do you know what should be the value of `this.id`? It might not be `0`. I tried a couple different possibilities, but Idk what should `this.id' evaluated to.

**Comment by jmfield2** [comment]
Ohh try otp-infoWidget-0

It's defined a couple of lines above :)

If that doesn't work try setting a js breakpoint to inspect the variables
at runtime

**Comment by jailby** [comment]
This is no working either. I fell like it's missing something

**Comment by jmfield2** [comment]
Hm. We are able to get this working? It seems to work for me when I:
"webapp.infoWidgets['otp-infoWidget-0'].show()" from the console

So, it seems like it would be:
`
<li class="mdl-menu__item" onClick="javascript:webapp.infoWidgets['otp-infoWidget-0'].show();" >Help</li> 
`

**Comment by jailby** [comment]
I knew it. I forgot the quotes ...

**Comment by jailby** [comment]
So now the icon legend widget is linked to the help button in the menu.

I also added a button feedback in the menu that open the widget containing the email address of @barbeau

**Comment by jailby** [comment]
With the last few change made I believe that we can merge this branch.

**Comment by jailby** [comment]
I actually noticed a problem on mobile.

The menu button is a little bit higher than earlier version. I don't know what caused this problem yet.

Screenshot:
image

I have the feeling that its when we changed style.css with Joseph.

**Comment by barbeau** [comment]
@jailby Yeah, the hamburger should be the same height as the USF logo.

**Comment by jailby** [comment]
I cannot figure out what changed, nor from which commit the problem appeared.

I checkout the first commit of this PR, which was working when I tested it, and it is not working either.
I am confuse and still looking for a solution to solve this problem.

I roll back every commit with:
`git checkout <commit> -b <newBranch>`

If anybody has some lead/ideas let me know.

**Comment by jmfield2** [comment]
Try the following patch (with patch -p0 <menu.txt) - I think it improves the height issue, but may not completely solve it..

[menu.txt](https://github.com/CUTR-at-USF/usf-mobullity/files/33961/menu.txt)

**Comment by jailby** [comment]
@jmfield2 Hey, can you check my last commit here?

I use style="vertical-align:middle;" to align the icons with their corresponding text. However it only align them vertically for some reason it is not working horizontally.

I tried it on [a minimal example](http://codepen.io/anon/pen/jbJXQP) and it's working there. Can you let me know if you have an idea of how to debug that?

**Comment by jmfield2** [comment]
So, I think what you need to do is apply vertical-align:middle to the li > i elements (the actual icon) which should align (vertically) the icon with the text next to it.  

To adjust the horizontal alignment (seems like you mean to move the icon to the left to make the spacing between the edge of the menu and the beginning of the text more balanced?) you'll need to adjust the LI padding and then play with the width and/or padding on the LI > I elements to get the desired effect.

**Comment by jailby** [comment]
I think you misunderstood what I meant. I'm going to explain with a screenshot it will be easier:

image

As you can see on the screenshot the text and the icon are aligned. This is due to the style="vertical-align:middle;" tag which I added on the li element in index.html.

However, (I don't know if it is obvious) the text of all the li elements have been flush to the top. I hovered with the mouse to show the limit at the top.

I would like to have them centered in the middle of the button(li element).

**Comment by jmfield2** [comment]
OK, I took a look at your branch and it looks like this is caused by:

.mdl-menu__item {
    line-height: 1;
}

When I remove the line-height (in firefox, at least), the text and icons are magically aligned vertically like you want 

Hopefully that works lol

**Comment by jailby** [comment]
Thanks for finding that. I tried so many different things that was always not working. 

I will try that tomorrow morning and I will let you know if it works.

**Comment by jailby** [comment]
I came in early to make sure I had time to finish it today. Here is my result:
image

Also, @jmfield2 I used style="vertical-align:middle;" in index.html. I didn't use style.css because after a couple of attempt it was not working. Should it be coded within the css or html is fine? (I'm pushing soon if you want to see exactly what I meant)

**Comment by jmfield2** [comment]
It really should be in the style.css mm did you try just assigning it to
the li elements with the material menu class? You might also need to add
!important at the end like:
Vertical-align: middle !important;

Which is also not great but a bit better than the inline way I think

**Comment by jailby** [comment]
I just tried with:

```
#li > i.elements {
    vertical-align:middle !important;
}
```

Am I missing something? This does not work (and I deleted the html tag).

**Comment by jmfield2** [comment]
Sorry - I think it should be:

li.mdl-menu > i, li.mdl-menu {

(the . means it selects all LI elements with "mdl-menu" class attribute, ">" means direct children of the LI matching <I> and class (again '.') "elements" )

So you don't need the # in front of li - that's only used to select an element by id attribute and it goes like: li#value-of-id  for e.g: `<li id="value-of-id">`

Also, if you decide to use a class for I, it looks like it needs to be: i.material-icons, right?

**Comment by jailby** [comment]
I wrote the following based on your comment (and deleted the html code corresponding):

```
li.mdl-menu > i.material-icons, li.mdl-menu {
    vertical-align:middle;
}
```

Only the text gets aligned in the middle of the button. The icons are still flush to the top (See screenshot below).
image

In your comment you said:
`">" means direct children of the LI matching`
Does the material-icons are actual children of li.mdl-menu? That might be why it does not get aligned.

**Comment by barbeau** [comment]
Awesome, thanks!

**Comment by barbeau** [comment]
Seems like this didn't deploy to mobullity.  @jmfield2 could you please take a look?

**Comment by jmfield2** [comment]
Fixed. Forgot the /y switch for the copy cmd and had to fix one other issue
w the cookbook

You may have to force refresh to reload styles.CSS etc

**Comment by barbeau** [comment]
Thanks!  Looks good now.

**Pull request merged**
