### PR TITLE
U itrip planner

### PR DESCRIPTION
**Pull request by jailby**

### CODE REVIEW

**Comment by jailby** [comment]
Screenshot for #234 :
image

Screenshot fro #206 :
image

**Comment by barbeau** [comment]
Cool!  Looks much better!  Looks like it saves some vertical space too.

**Comment by jailby** [comment]
Yes it does. (The button is smaller.)

**Comment by jmfield2** [comment]
This might be OK, but I was thinking you would just need to remove the '.button()' call like:

```
-        $('#'+this.id+'-button').button().click(function() {
+        $('#'+this.id+'-button').click(function() {
```

It seems to work for me for removing the styling but retaining the click handler and I think is preferable to using .onclick directly since the .click() way is attached via jQuery instead of directly on the DOM

**Comment by jailby** [comment]
@jmfield2 I modified accordingly to what your previous comment and tested it. It works fine.

**Pull request merged**
