### PR TITLE
Add collapsible layers groups

### LINKED ISSUE #181: Athletic facilities
This issue propose a new layer which is "Athletic Facilities". Umbrella issue: #177 

In the following map some Athletic Facilities are shown:
image

Other that could be added are for example:
The outdoor running track, magnolia field, fowler field, outdoor basketball court, outdoor tennis court, etc...

**Markers:** 
In this case there is multiple parameter to consider. This can be a building (e.g.: REC center), or a space outside (e.g.: magnolia fields). Howeve,r it is not always a polygon (e.g.: outdoor running track).

### LINKED ISSUE #182: Layer widget size
In the future we might run into a problem with the size of the layers widget.

If all the layer from the issue #177 are added the widget will be huge.

To avoid this problem we should prepare for it by first implementing a way to manage the size of the widget layer content.

I believe that having a plus/minus "+"/"-" for each layer category to collapse the corresponding category seem a good idea.

Also, I believe the widget should have a fixed sized and when a user uncollapse many categor this user should have the option scroll down within the widget.

### PR DESCRIPTION
**Pull request by jmfield2**
This uses jQuery to handle the open and close toggling.  The icon is fontawesome chevron.

Each open/close action triggers a GA event, and saves the current state of each group into the "layersUsed" cookie for restoring upon subsequent loads.

On first load, desktop clients should see all available groups open by default, and mobile clients will only see the top USF routes open.

Fixes #182 

See this screenshot for how it is supposed to look:
layers gray

Also fixes #181, #366, #178, #249
Some of these might need some OSM updates to reflect current options via official USF maps, etc
Example build-config:
```
{
 pois: { amenity: {
                     parking: [],
                     bicycle_repair_station: [],
                     bicycle_parking: ["inTampaCampus"],
                     charging_station: [],
                     fast_food: [],
                     restaurant: [],
                     post_box: []
                  },
         shop:    {
                     supermarket: [],
                     copyshop: ["service:self=yes"]
                  },
         sport: {
                    soccer: [],
                    baseball: [],
                    football: [],
                    softball: [],
                    basketball: [],
                    tennis: [],
                    running: []
                },
         tourism: {
                    terminal: []
                }
        }
}
```

Also, other updates to the POI system have been added:
- inTampaCampus and key=value condition checking for individual POI keys
- add logical OR comma-delimited queries from @mohangandhiGH 

Related to #177

### CODE REVIEW

**Comment by jmfield2** [comment]
https://www.openstreetmap.org/changeset/43434494
and
https://www.openstreetmap.org/changeset/43434835

**Comment by barbeau** [comment]
Looks like this deployed to Mobility but it's really laggy, almost nonresponsive.   Could you give it a look when you have a chance?

**Comment by jmfield2** [comment]
You aren't seeing the slowness in the entire widget, right? I see lag in specifically the new on-campus living group, and a little bit in the bike racks, but the others seem to be fine for me.

If that is the same as what you're seeing, I suspect it is because of the larger tampa graph and it trying to render markers for the entire area...  

It seems like there are two options: 
1) (quick fix) restrict the new markers to the tampa campus only, 
2) add a bounding box to the POI endpoint so that only the visible area loads markers at a time.

**Comment by barbeau** [comment]
Correct,  specific to on-campus living layers. I would say let's do 1) for
now so we can get it into production and 2) over next week's. I also see an
issue with expanding categories on mobile and bottom being cut off, will
post screenshots later.

**Pull request merged**
