### PR TITLE
Fix 45 & 65 centering the map on relevant coordinates. Fix 69 bug when zooming too much.

### LINKED ISSUE #45: When using itinerary link, center map on trip plan
Currently, when using a link for a trip:
http://mobullity.forest.usf.edu/index.html?module=planner&fromPlace=28.05456022682711%2C-82.41329669952393&toPlace=CUT%3A%3A28.058091807150525%2C-82.41654753684998&time=9%3A19am&date=08-12-2015&mode=CAR

...the map centers on the user's location:

image

We should center of the results of the trip plan instead:

image

### LINKED ISSUE #65: Zoom on USF campus
If users don't share their location the map will give a super zoomed out view of West Florida.
Screenshot from Firefox:
image

When users don't share their location the map should be zoomed on the USF campus. Then, users can manually adjust to their preferences.

Related to: https://github.com/CUTR-at-USF/usf-mobullity/issues/45

### LINKED ISSUE #69: User maximum zoom-in level not working
Currently the user can zoom-in until the level 8:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/config.js#L73

This cause a bug which cause the tile to all appear gray (no relevant screenshot).

I made some test and it appear to me that only the level 8 has this problem. Thus, I'm proposing to change the "minZoom" attribute to 9.
The fix is on the way.

### PR DESCRIPTION
**Pull request by jailby**
fixes #65 : The map now is center on USF campus when a user does not share his location. 
Value of the attribute "zoomToFitResults" set at "true".
fixes #45 : The map now center on the trip planned by the user. 
Modification of the center of the map by modifying the attribute "initLatLng".
Deletion of the code forcing to fit the boundary which caused the zoomed out view.
fixes #69 : The user cannot zoom too much.
Change the "minZoom" attribute to 9 because 8 cause the map to be all gray and necessitate multiple zoom out to be restored.

### CODE REVIEW

**Comment by jailby** [comment]
It seem like it didn't link the PR to the issues. Should I add the sign pound '#' before the numbers in the title of the PR?

**Comment by jmfield2** [comment]
Looks good.  Do you think we should also add a config option for the closer default zoom when gps is available @ https://github.com/jailby/usf-mobullity/blob/mobullityrebase_issue65/src/client/js/otp/core/Map.js#L152 ?  I tend to think yes.

Also:
https://github.com/jailby/usf-mobullity/blob/mobullityrebase_issue65/src/client/js/otp/core/Map.js#L132
and
https://github.com/jailby/usf-mobullity/blob/mobullityrebase_issue65/src/client/js/otp/core/Map.js#L124

should probably be changed to reflect the otp.config.initZoom property instead of being hard-coded, right?

**Comment by barbeau** [comment]
+1 for closer default zoom when using GPS - would definitely help on mobile.

**Comment by jmfield2** [comment]
I also forgot one small thing - the break @ 
https://github.com/jailby/usf-mobullity/blob/mobullityrebase_issue65/src/client/js/otp/core/Map.js#L103 seems awkward to me and doesn't follow the rest of the key: value pattern - was there a reason to keep it that way?

One last thing - could possibly be moved to it's own issue, but maybe not:
https://github.com/jailby/usf-mobullity/blob/mobullityrebase_issue65/src/client/js/otp/core/Map.js#L151

and 

https://github.com/jailby/usf-mobullity/blob/mobullityrebase_issue65/src/client/js/otp/core/Map.js#L118

I think line 118 should be moved to either 127 or 135 to handle a case where perhaps the gps fires with an inaccurate result for some reason and then fires again with greater accuracy in which case the marker will be added, but no zoom will occur.  Has anyone seen behavior like this?  It seems like it would be rare if it did happen at all but just throwing it out there because it might be more appropriate to increment the count there instead of where it does now - or at least to test it further.

**Comment by barbeau** [comment]
> I think line 118 should be moved to either 127 or 135 to handle a case where perhaps the gps fires with an inaccurate result for some reason and then fires again with greater accuracy in which case the marker will be added, but no zoom will occur. Has anyone seen behavior like this?

I've seen this in native Android apps (especially lower-end devices) with enough frequency that it needs to be handled, but haven't really looked at Leaflet/web app for this issue.  I'm assuming the location engine for something like Chrome on Android uses the same underlying source as the native apps, so we should probably handle this situation in MoBullity too.

**Comment by jailby** [comment]
@jmfield2 @barbeau Let me know if now it is good to merge.

I didn't do anything about line 118. We can discuss that during Friday's meeting.

**Comment by jmfield2** [comment]
Looks good to me

**Comment by barbeau** [comment]
Looks good to me!  Thanks @jailby!

**Pull request merged**
