### PR TITLE
Fix to wrong size of the trip summary in "itinerary returned" widget and Trip summary colour depending on the mode.

### LINKED ISSUE #260: Trip summary color depending on the mode
In the "itinerary returned" widget there is a trip summary at the top showing, through logos, the modes (walk, bus, bicycle)  that the user will have to take to follow the trip.

The background for these logos is different for depending on the mode:
Walk: gray
Bicycle: Blue
Bus: Green

This problem need to be fixed for the following mode:
- [ ] Bycicle
  Bicycle should be change to be the same as the color use to show the trip on the map (I believe its purple)
  Screenshot:
  image
  @jmfield2 if you could comment with the color you used. If I'm not wrong you did changed that a while ago. I tried to find it back in the commit but I don't remember the time period.

**Related issue:**
While fixing this issue for the bicycle mode the logo need to be made more visible. Detail on this issue at #242 
- [ ] Buses
  For the Bus mode the color should be the color attributed for each route in the layer widget.
  (e.g.: route D is red)
  Screenshot for a trip with a bus:
  image
  Screenshot of the layer widget color for buses.:
  image
  Also, when two bus are necessary to take in order to get to the destination it is not clear for the user that he need to step out of the bus at some point from the colored route:
  image
  I hover the route in the itinerary returned widget to show it better:
  image

This will enable more visibility. A user could identify much quicker which bus he has to take. Also we are using the same colors than the one use by the Bullrunner so a user can associate these color with the color he can see irl.

### PR DESCRIPTION
**Pull request by anilreddy1**
Changed itinerary widget logos to have minimum size and colors of routes and widgets logos for more visibility.
#261 In the "itinerary returned" widget, there is a trip summary at the top showing, through logos, the modes(bus,walk,bicycle) that the user have to take to follow the trip. Sometimes these logos are too small and not visible properly and even div width varies, so changed these logos to have a minimum size and fixed the div to have constant size.
#260 All the bullrunner bus routes are shown with same color in tripplanner, so when two bus are necessary to take in order to get to the destination it is not clear for the user that he need to step out of the bus at some point from the colored route. Changed the bull runner routes to have different colors(same colors used in layers) and changed the widget logo colors accordingly. And changed the bicycle route and widget logo color to enable more visibility.

Fixes #260 #261

### CODE REVIEW

**Comment by jmfield2** [comment]
I think this looks pretty good.  Two things:

Since we use git, you can just delete the old lines instead of commenting them.
Also, add a space in the commit messages if you can ("Fixes #260 #261"), or at least add that into the description for the PR.  It might be helpful to add a bit more description into the commit message too.

Otherwise, good job!

**Comment by anilreddy1** [comment]
Thanks Joseph! I will follow these things from next pull request.

**Comment by jmfield2** [comment]
Thanks! I think this is good now, right?

**Comment by anilreddy1** [comment]
Yeah:)

**Pull request merged**
