### PR TITLE
Ucm bugs

### PR DESCRIPTION
**Pull request by jailby**
This PR fixed the issue received from ucm concerning the send feedback widget

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks @jailby!  Can you please include screenshots here of how it looks before and after these changes?

**Comment by jailby** [comment]
**Before:**
image

**After:**
The looks of the widget:
image

The email (this will depend on the user and the setup of the browser):
image

**Comment by jmfield2** [comment]
Is this ready to merge?  I think the code looks fine so far

**Comment by barbeau** [comment]
+1

**Pull request merged**
