### PR TITLE
Color changes

### LINKED ISSUE #107: Change colors to official USF colors
The new USF logo is looking good:
https://github.com/CUTR-at-USF/usf-mobullity/pull/106#issuecomment-151530961

image

However, it now clear that we aren't using official USF colors in the site - at least for the light green used for the widget headers and main header underline.

We should change to using just the official USF colors for green and gold, as defined here:
http://usfweb4.usf.edu/ucm/marketing/colors.aspx

Green is:

> PMS 342 C/PMS 342 CP
> CMYK: C93 M10 Y75 K43
> HTML: 006747
> RGB: R0 G103 B71

Gold is:

> PMS 4535 C/PMS 4535 CP
> CMYK: C6 M8 Y35 K12
> HTML: CFC493
> RGB: R207 G196 B147

### LINKED ISSUE #124: Better visibility of "switch fields" button
From Renee Hunt at USF:

> The button to the right of the Start and End fields looks like a little phone rather than arrows.  Maybe take out the dark background behind the icon and make the arrows black on the gray button. 

I agree, it's currently hard to see.  I agree that making the arrow black on the gray button background is probably the best solution.

### PR DESCRIPTION
**Pull request by jailby**
These changes fixes #107.

CSS specification for the trip planner and layers widget have been group for more consistency and also border have been added due to the color change that made the widget header look like they were overlapping the main bar.

I'm going to create a separate issue for the trip widget itself because #107  is about the overall colors of the website. Also, the modification are more complicated than what I thought. I will create a separate branch to resolve #124, #123, and the incoming issue about padding.

I have included some screenshot to remind you how the trip planner and layers widgets look:

Trip planner widget:
image

Layers widget:
image

### CODE REVIEW

**Comment by jailby** [comment]
I'm a little bit confuse.

I couldn't see the first three commits on my remote repository.
I'm assuming that there were on my local repository and I actually pushed them with the commit https://github.com/jailby/usf-mobullity/commit/800138b65c923e7ccf2fa2687ce14d3c2122a9b6.

Please do not merge yet. I would like to try to figure out what happen and fix it.

**Comment by barbeau** [comment]
@jailby FYI - you can easily see a compact history of your local Git repo at the command line with:
`git log --oneline`.

**Comment by barbeau** [comment]
@jailby Also, once you fix your local branch (either create a new one, or fix the current one), you can force-push to your remote branch to update the contents of this PR.

For example, if you create a new local branch `colorChanges-fixed`, you can do this to update this PR:

`git push origin -f colorChanges-fixed:colorChanges`

Hopefully I got that syntax right :).  This will overwrite the current contents of your remote repo `colorChanges` branch, which will also update this PR with the same contents.

**Comment by jailby** [comment]
Oh nice I didn't know about `git log --oneline`.

I see what you mean but I want to keep the last three commit and get rid off the first three.

I believe that if I just revert these commit it should work, right?

**Comment by jmfield2** [comment]
I think that would work - just add another commit with the revert of the first three..  A better way is probably to create another branch and `git cherry-pick` only the three commits that you want and force push like sean said.

**Comment by jailby** [comment]
Yes @jmfield2 cherry pick is a better solution.

I was looking into it and reverting creates conflict. I'm going to cherry pick the last three and force push like @barbeau indicated. I think that the best solution.

I already started and I think I found the syntax to do so.

**Comment by jailby** [comment]
Ok so cherry picking worked and I was able to push here but I'm not really sure why there is a conflict.

The conflict mark the whole file. I resolve the conflict and try to push but it has been rejected because " a pushed branch tip is behind its remote". So I need to figure out what that mean and try to fix it.

**Comment by barbeau** [comment]
If you get a whole file conflict it's likely your line endings conflicting with the existing code.

" a pushed branch tip is behind its remote" means that there are commits in "CUTR-at-USF:mobullityrebase" branch that aren't in your local branch.  You'll need to pull commits from "CUTR-at-USF:mobullityrebase" to your local "mobullityrebase" branch.

Assuming you've already added the CUTR-at-USF repo as a remote named "upstream" in your local Git instance, I'd do something like this:
- `git checkout mobullityrebase`
- `git pull upstream mobullityrebase`
- `git checkout colorChanges`
- `git checkout -b colorChanges2` // Just to make sure if something goes wrong, you still have colorChanges
- `git rebase --ignore-whitespace mobullityrebase`

This should ignore any whitespace changes and get rid of that conflict.  You'll need to walk through the rebase steps - ideally you'll want to squash the 3 commits into a single commit.  It's been a while since I've rebased from command line (I used IntelliJ or Android Studio), but let us know if you hit problems.
- `git push origin -f colorChanges2:colorChanges`

You'll need to check your local line endings settings - it's been a while since I've configured this on Git, so it might require some experimentation on your end.

**Comment by jailby** [comment]
Yeah \o/
I made it.

I'm going to check the code and make sure I didn't do anything wrong.
@jmfield2 if you also can take a look because after all these change I may not see something important.

**Comment by barbeau** [comment]
Just talked to @jailby - there are some whitespace issues he's still working on.

**Comment by jmfield2** [comment]
So, there indeed seem to be whitespace or line ending issues with the style.css file... I was able to get a patch against upstream by manually ignoring the whitespace with `diff -w old new`

With that, you should be able to just apply it (patch -p0 <style.txt) and then push -f 

Hopefully that helps 

Note with the patch, I think I made a change sometime within the past month that is in upstream (related to the Welcome Widget background color) that might get undone if you use the manual patch method .. so just review it carefully

**Comment by jailby** [comment]
So when applying the patch I will probably have conflict and I need to check carefully to manually merge them right?

Also can you send me the patch? I assume I have to use `git apply <nameOfPatch>`, right?

Also do I need to revert the commit 650b161 and then apply the patch or can I directly apply the patch?

**Comment by jmfield2** [comment]
So what I did was checkout your color change branch, copy styles.CSS out,
then checkout upstream and run diff -uw on the old to the new style.CSS

If you save the output of that >out.txt

Then you should be able to run patch -p0 <out.txt

Might work using git but haven't tried that.. I can try to do the patch but
I'm not sure what changed and I usually mess up the order for the files
when I run diff

If you do that it won't conflict w git I don't think but it might erase
changes made between your branch and upstream which I think is just the
welcome fix

**Comment by jailby** [comment]
So I have been trying to do that in different way but every time the patch fail because of different line ending.

I'm still working on it I will keep updating.

**Pull request closed without merging**
