### PR TITLE
Field validation

### PR DESCRIPTION
**Pull request by jailby**
Both the time and the date are validated. The date is also updated if the user enter it manually.

The validation happens twice:
-> First time. For the time it happens when the user click outside of the time input field (loose focus) whereas for the date the validation happens when the datepicker is closed. The datepicker is also closed when the user loose focus.

-> Second time. When the user click on "Plan Your Trip" both values are being validated.

Screenshot of the message:
image

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks @jailby!  Does this seem to work fine on mobile too?

**Comment by jailby** [comment]
Screenshots for mobile:

image

image

**Comment by barbeau** [comment]
Is the title cut off in your view on the phone too?  Does this happen with the other dialogs?

**Comment by jailby** [comment]
I erase my IP address from the screenshot.

It will say "maps.usf.edu says:" instead of "white box says:".

**Pull request merged**
